diffssf <- with(HW2Dat,still-flow)
qplot(diffssf, xlab="Difference in Average Daily Water Drunk for Still-Flowing Water(mL)", geom="histogram")
(sd1 <- sd(diffssf))
(Ybar1 <- mean(diffssf))
(n1 <- length(diffssf))
(se_Ybar1 <- sd1/sqrt(n1))
(tstat1 <- Ybar1/se_Ybar1)
t.test(Zinc~Group, data=ex0125, var.equal=TRUE, alternative="less")
t.test(Zinc~Group, data=ex0125, var.equal=TRUE)